version: "3.3"
services:
  frontend:
    build: ./frontend
    container_name: foodyfrontend-container
    image: vkalavarkar/foodyfront:v1
    ports:
      - "5173:5173"

  backend:
    build: ./backend
    container_name: foodybackend-container
    image: vkalavarkar/foodyback:v1
    ports:
      - "4000:4000"